## To run this notebook correctly, make sure the main version of zarr is installed!! Not the Sharding Pull Request

In [1]:
import zarr # Check version
zarr.__version__

'2.13.0a2.dev42+dirty'

Zarr Sharding pull request should show '0.0.0'

If it says e.g. 2.13.2, then you're running on the "proper" published version (without Sharding support as of 28-Sept-2022)

### 1. I wanna test partial_decompression by accessing a random index

In [2]:
import numpy as np


numpy_arr = np.empty((65536, 16384), dtype=np.int32) # ~3GB
original_shape = numpy_arr.shape

# 50k x 150k int32 is limit of M1 Pro 32GB
#
for i in range(numpy_arr.shape[0]):
#     numpy_arr[i][:] = list(range(original_shape[1]*i, original_shape[1]*(i+1)))
    numpy_arr[i][:] = np.random.randint(low=0, high=original_shape[0], size=original_shape[1])

In [3]:
print("Memory used: ", numpy_arr.nbytes / 1024 / 1024 / 1024, " GB")

Memory used:  4.0  GB


In [4]:
numpy_arr[0][0] = -numpy_arr[0][0]

In [5]:
numpy_arr[0][0:10]

array([-42801,  15695,  49730,  17004,  16136,   6168,  40092,  10717,
        28964,    167], dtype=int32)

## Following code found in build/lib/zarr/tests/test_core.py:2605

In [ ]:
z = zarr.core.Array(FSStore("temp-code-FSS"), 

In [19]:
z = create_array(shape=1000000, chunks=100_000)
z[40_000:80_000] = 1
path = None if self.version == 2 else z.path
b = Array(z.store, path=path, read_only=True, partial_decompress=True)

NameError: name 'create_array' is not defined

In [6]:
# So Let's use a weak compressor
from numcodecs import Blosc
weak_compressor = Blosc(cname='lz4', shuffle=Blosc.SHUFFLE, clevel=5)

weak_compressor.decode_partial

<bound method Blosc.decode_partial of Blosc(cname='lz4', clevel=5, shuffle=SHUFFLE, blocksize=0)>

In [7]:
dir(weak_compressor)

['AUTOSHUFFLE',
 'BITSHUFFLE',
 'NOSHUFFLE',
 'SHUFFLE',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_cname_bytes',
 'blocksize',
 'clevel',
 'cname',
 'codec_id',
 'decode',
 'decode_partial',
 'encode',
 'from_config',
 'get_config',
 'max_buffer_size',
 'shuffle']

In [10]:
fsstore = zarr.storage.FSStore('./fsstore3')#partial_decompress=True, overwrite=True)
fsstore_chunk = zarr.storage.FSStore('./fsstore-chunk3', partial_decompress=True)
# dir(fsstore) # No _partial_decompress or similar in dir

In [11]:
# Let's make chunks really large to test partial decompression

chunk_size=(4096,4096)

# Reached max chunk size
zarr_index_list = zarr.array(numpy_arr, store=fsstore, chunk_store = fsstore_chunk, partial_decompress=True, chunks=chunk_size, dtype='i4')# compressor=weak_compressor, 
# z = zarr.zeros((10000,10000), chunks=(1000,1000), dtype='i4')

print("_partial_decompress: ", zarr_index_list._partial_decompress)
zarr_index_list.info

_partial_decompress:  False


Type               : zarr.core.Array
Data type          : int32
Shape              : (65536, 16384)
Chunk shape        : (4096, 4096)
Order              : C
Read-only          : False
Compressor         : Blosc(cname='lz4', clevel=5, shuffle=SHUFFLE, blocksize=0)
Store type         : zarr.storage.FSStore
Chunk store type   : zarr.storage.FSStore
No. bytes          : 4294967296 (4.0G)
No. bytes stored   : 2156234075 (2.0G)
Storage ratio      : 2.0
Chunks initialized : 64/64

<font color="red">Not sure why it's ignoring partial_decompress. Maybe it just works on open()/read()</font>

In [12]:
dir(zarr_index_list)

['__array__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_append_nosync',
 '_attrs',
 '_cache_metadata',
 '_cdata_shape',
 '_chunk_delitem',
 '_chunk_delitems',
 '_chunk_getitem',
 '_chunk_getitems',
 '_chunk_key',
 '_chunk_setitem',
 '_chunk_setitem_nosync',
 '_chunk_setitems',
 '_chunk_store',
 '_chunks',
 '_compressor',
 '_decode_chunk',
 '_dimension_separator',
 '_dtype',
 '_encode_chunk',
 '_fill_value',
 '_filters',
 '_flush_metadata_nosync',
 '_get_basic_selection_nd',
 '_get_basic_selection_zd',
 '_get_selection',
 '_info_items_nosync',
 '_info_reporter',
 '_is_view

<font color="orange">^^ Has _partial_decompress as attribute</font>

In [13]:
del numpy_arr # Don't need this anymore - save 3GB

In [8]:
# # example-zarr is actually a folder
# # z1 = zarr.open('./example-zarr', mode='w', shape=original_shape, chunks=(10000,10000), dtype='f8', partial_decompress=True)
# zarr.save('./example-zarr', zarr_index_list)
# # open() doesn't actually write anything, hence it being so fast

In [14]:
# USE FSSTORE IF YOU WANT PARTIAL_DECOMPRESS TO WORK!!
# This cell does what open() does. But open() only uses DirectoryStore

z = zarr.create(store=fsstore, shape=original_shape, dtype='f8')

ContainsArrayError: path '' contains an array

In [15]:
# zarr.save('./example-zarr', zarr_index_list)
zarr.save(fsstore, zarr_index_list, chunk_store=fsstore_chunk)

In [16]:
# Read array from disk
load_disk_partial_decompress = zarr.open(fsstore, mode="r") # partial_decompress=True - unknown argument FOR GROUPS

In [17]:
print("_partial_decompress: ", load_disk_partial_decompress._partial_decompress)

AttributeError: 

In [29]:
load_disk_partial_decompress.info

Name        : /
Type        : zarr.hierarchy.Group
Read-only   : True
Store type  : zarr.storage.FSStore
No. members : 2
No. arrays  : 2
No. groups  : 0
Arrays      : arr_0, chunk_store

In [31]:
load_disk_partial_decompress["chunk_store"] # Group contains 2 elements - access chunk store using this indexing way

<zarr.core.Array '/chunk_store' (64,) <U4 read-only>

In [32]:
load_disk_partial_decompress["chunk_store"].info

Name               : /chunk_store
Type               : zarr.core.Array
Data type          : <U4
Shape              : (64,)
Chunk shape        : (64,)
Order              : C
Read-only          : True
Compressor         : Blosc(cname='lz4', clevel=5, shuffle=SHUFFLE, blocksize=0)
Store type         : zarr.storage.FSStore
No. bytes          : 1024
No. bytes stored   : 455
Storage ratio      : 2.3
Chunks initialized : 1/1

In [33]:
load_disk_partial_decompress["chunk_store"]._partial_decompress

False

In [81]:
# USE FSSTORE IF YOU WANT PARTIAL_DECOMPRESS TO WORK!!

fsstore = zarr.storage.FSStore('./fsstore-partial-zarr', partial_decompress=True)
z = zarr.create(store=fsstore, shape=original_shape, dtype='f8', partial_decompress=True)

In [82]:
# zarr.save('./example-zarr', zarr_index_list)
zarr.save(fsstore, zarr_index_list, partial_decompress=True)

In [86]:
%%timeit
# Read array from disk
load_disk_partial_decompress = zarr.open(fsstore, mode="r", partial_decompress=True)
# load_disk_partial_decompress.info
# load_disk_partial_decompress._partial_decompress

TypeError: open_group() got an unexpected keyword argument 'partial_decompress'

<font color="orange"> Notice how compression changes, much higher Ratio. Chunks <10MB in size now</font>

Sometimes chunks not even initialized? Sometimes 2 arrays are written to disk (i.e. a group). Not sure why

In [30]:
# # Read it properly, without partial_decompressing chunks
# # load_disk_normally = zarr.open("./example-zarr", mode="r", partial_decompress=False)
# load_disk_normally = zarr.open(fsstore, mode="r", partial_decompress=False)
# load_disk_normally.info

In [45]:
# Read it properly, without partial_decompressing chunks
# load_disk_normally = zarr.open("./example-zarr", mode="r", partial_decompress=False)
load_disk_normally = zarr.open(fsstore, mode="r", partial_decompress=False)
load_disk_normally.info

Type               : zarr.core.Array
Data type          : int32
Shape              : (65536, 16384)
Chunk shape        : (4096, 4096)
Order              : C
Read-only          : True
Compressor         : Blosc(cname='lz4', clevel=5, shuffle=SHUFFLE, blocksize=0)
Store type         : zarr.storage.FSStore
No. bytes          : 4294967296 (4.0G)
No. bytes stored   : 2156234073 (2.0G)
Storage ratio      : 2.0
Chunks initialized : 64/64

Both look identical so far

In [46]:
load_disk_partial_decompress[0, 100]

22847

In [47]:
load_disk_normally[0, 100]

22847

^^^ Should be 100

### Let's test random access of chunks by index

In [48]:
rand_indices = np.random.randint(low=0, high=original_shape[0], size=50)

In [52]:
%%timeit
# Read randomly from first chunk, Using partial decompression

for index in rand_indices:
    load_disk_partial_decompress[0, index]

627 ms ± 4.13 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [53]:
%%timeit
# Read randomly from first chunk, Not using partial decompression

for index in rand_indices:
    load_disk_normally[0, index]

629 ms ± 8.57 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


## <font color="orange"> New experiment: access one point per chunk in the whole array</font>

In [60]:
# TODO get this programmatically
nr_chunks = 64

In [63]:
rand_indices_whole_array = []

for i in range(nr_chunks):
    rand_indices_whole_array.append(np.random.randint(low=i*chunk_size[0], high=(i+1)*chunk_size[1]))

rand_indices_whole_array = np.array(rand_indices_whole_array)
rand_indices_whole_array

array([     0,   7334,  10148,  13658,  17305,  21667,  24862,  31072,
        35241,  38359,  44806,  46999,  52829,  55998,  57702,  63836,
        66686,  70183,  77228,  81751,  82734,  89051,  93620,  96894,
        99899, 103138, 107660, 111667, 117444, 121965, 125533, 127237,
       131702, 138435, 141282, 143504, 149455, 152804, 158614, 162882,
       164650, 169870, 173882, 178925, 181082, 186865, 189810, 196288,
       198489, 203189, 205845, 212636, 213285, 219258, 225189, 228728,
       232427, 236474, 240707, 241861, 246274, 252591, 256284, 259575])

In [71]:
# rand_indices_whole = np.random.randint(low=0, high=chunk_size[0], size=nr_chunks)
# rand_indices_whole

In [75]:
%%timeit
# Read randomly from whole array, randomly 1 point from each chunk
# TODO Don't know if my indexing is correct!!

for index in rand_indices_whole_array:
    load_disk_partial_decompress[int(index / original_shape[1]), index % original_shape[1]]

801 ms ± 925 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [70]:
%%timeit
# Read randomly from whole array, randomly 1 point from each chunk
# TODO Don't know if my indexing is correct!!

for index in rand_indices_whole_array:
    load_disk_normally[int(index / original_shape[1]), index % original_shape[1]]

804 ms ± 7.66 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [72]:
load_disk_partial_decompress.info

Type               : zarr.core.Array
Data type          : int32
Shape              : (65536, 16384)
Chunk shape        : (4096, 4096)
Order              : C
Read-only          : True
Compressor         : Blosc(cname='lz4', clevel=5, shuffle=SHUFFLE, blocksize=0)
Store type         : zarr.storage.FSStore
No. bytes          : 4294967296 (4.0G)
No. bytes stored   : 2156234073 (2.0G)
Storage ratio      : 2.0
Chunks initialized : 64/64

In [73]:
load_disk_normally.info

Type               : zarr.core.Array
Data type          : int32
Shape              : (65536, 16384)
Chunk shape        : (4096, 4096)
Order              : C
Read-only          : True
Compressor         : Blosc(cname='lz4', clevel=5, shuffle=SHUFFLE, blocksize=0)
Store type         : zarr.storage.FSStore
No. bytes          : 4294967296 (4.0G)
No. bytes stored   : 2156234073 (2.0G)
Storage ratio      : 2.0
Chunks initialized : 64/64

### Let's test advanced mask indexing

In [54]:
# Create a 0-1 boolean mask with size same as Whole array
#    Don't know how to do just 1 chunk masking
bool_mask = np.random.randint(low=0, high=2, size=original_shape, dtype=bool)
bool_mask

array([[ True, False, False, ...,  True, False,  True],
       [ True,  True,  True, ..., False, False,  True],
       [False,  True, False, ..., False,  True, False],
       ...,
       [ True,  True, False, ..., False,  True, False],
       [ True,  True, False, ..., False,  True, False],
       [ True,  True, False, ..., False, False, False]])

In [55]:
%%timeit
# Partial decompress

# _ to prevent printing
_ = load_disk_partial_decompress.get_mask_selection(bool_mask)

KeyboardInterrupt: 

In [ ]:
%%timeit
# NO Partial decompress

# _ to prevent printing
_ = load_disk_normally.get_mask_selection(bool_mask)

#### <font color="orange">Trying Compressors. Irrelevant</font>

In [17]:
!ls

example-zarr         tutorials            zarr_python
example.zarr         zarr-explore-1.ipynb


In [ ]:
# # Check if reading from file == original array
# import numpy as np

# np.all(z[:] == z2[:])

In [18]:
# Blosc is one of the preconditions of partial_decompress
# https://zarr.readthedocs.io/en/stable/api/core.html
from numcodecs import Blosc

bloccc = Blosc(clevel=9)

In [19]:
z_compressed = zarr.array(zarr_index_list, compressor = bloccc)

In [20]:
z_compressed.compressor

Blosc(cname='lz4', clevel=9, shuffle=SHUFFLE, blocksize=0)

In [21]:
z_compressed

<zarr.core.Array (10000, 10000) int64>

In [22]:
zarr.save('./example.zarr', z_compressed)

In [15]:
z2



KeyboardInterrupt

